baseurl = "/"
defaultContentLanguage = "en"
destination = "../dist/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
hrefTargetBlank = false
languageCode = "en-us"
languageLang = "en"
relativeURLs = false
title = "My New Hugo Site"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputs]
home = ["HTML", "RSS", "Algolia"]
[params]
author = "Harry Cresswell"
description = "Write an awesome description for your new site here. You can edit this\nline in config.yml. It will appear in your document head meta (for\nGoogle search results) and in your RSS feed description.\n"
[params.algolia]
params = ["featuredimage", "categories", "tags"]
vars = ["featuredimage", "title", "summary", "date", "publishdate", "expirydate", "permalink", "tags"]
