---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- hugo/content/posts/seven.md
- hugo/content/posts/my-sixth-post.md
- hugo/content/posts/my-fifth-post.md
