# Configures CSS Linting
# https://stylelint.io/
extends:
    - stylelint-config-standard
    - stylelint-config-sass-guidelines
plugins:
    - stylelint-scss
    - stylelint-no-unsupported-browser-features
defaultSeverity: warning
rules:
    plugin/no-unsupported-browser-features:
        - true
        - ignore: []
          severity: warning
    scss/at-extend-no-missing-placeholder: true
